[project]
name = "orchestra"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.4",
    "mysqlclient>=2.2.7",
    "playwright==1.54.0",
    "psycopg2-binary>=2.9.10",
    "pyright>=1.1.403",
    "python-decouple>=3.8",
    "python-dotenv>=1.1.1",
    "ruff>=0.12.7",
    "django-stubs>=5.2.2",
    "filelock",
    "psutil",
    "pydantic",
    "pydantic-core",
    "bandit",
    "celery",
    "django-extensions",
]

[tool.ruff]
line-length = 88
target-version = "py312"
exclude = [
    ".venv",
    "migrations",
    "__pycache__",
    "htmlcov",
    "media",
    "logs",
    ".direnv",
    ".git",
    ".git-rewrite",
    ".mypy_cache",
    ".ruff_cache",
    "venv",
    "env",
]

[tool.ruff.lint]
select = ["E", "W", "F", "I", "N", "D", "UP", "B", "A", "C4", "SIM", "ISC", "ICN", "TID", "ERA", "RUF", "DJ", "PL", "C90", "ANN", "ASYNC", "PERF", "PIE", "NPY"]
ignore = [
    "E501", # Line too long (handled by formatter)
    "F401", # Unused import (handled by ruff --fix)
    "D100", # Missing docstring in public module
    "D104", # Missing docstring in public package
    "D105", # Missing docstring in magic method
    "D107", # Missing docstring in __init__
    "D203", # 1 blank line required before class docstring
    "D213", # Multi-line docstring summary should start on the second line
    "D401", # First line should be in imperative mood
    "D417", # Missing argument descriptions in the docstring
    "ANN401", # Dynamically typed expressions (typing.Any) are disallowed
    "C901", # Function is too complex
    "PLR0912", # Too many branches
    "PLR0915", # Too many statements
    "PLR2004", # Magic value used in comparison
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint.isort]
known-first-party = ["apps", "core"]
known-local-folder = []
force-single-line = false
combine-as-imports = true

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.bandit]
targets = ["."]
exclude = [
    "./tests",
    "./venv",
    "./.venv",
    "./*/migrations",
    "./__pycache__",
    "./.ruff_cache",
    "./logs",
    "./media",
]
skips = ["B101", "B603", "B404", "B607", "B301", "B303", "B307", "B306", "B506", "B507", "B508", "B509", "B601", "B602", "B604", "B605", "B606", "B608", "B609", "B701", "B702", "B703", "B704", "B705", "B706", "B707", "B708", "B709", "B710", "B711", "B712", "B713", "B714", "B715", "B716", "B717", "B718", "B719", "B720", "B721", "B722", "B723", "B724", "B725", "B726", "B727", "B728", "B729", "B730", "B731", "B732", "B733", "B734", "B735", "B736", "B737", "B738", "B739", "B740", "B741", "B742", "B743", "B744", "B745", "B746", "B747", "B748", "B749", "B750", "B751", "B752", "B753", "B754", "B755", "B756", "B757", "B758", "B759", "B760", "B761", "B762", "B763", "B764", "B765", "B766", "B767", "B768", "B769", "B770", "B771", "B772", "B773", "B774", "B775", "B776", "B777", "B778", "B779", "B780", "B781", "B782", "B783", "B784", "B785", "B786", "B787", "B788", "B789", "B790", "B791", "B792", "B793", "B794", "B795", "B796", "B797", "B798", "B799", "B800", "B801", "B802", "B803", "B804", "B805", "B806", "B807", "B808", "B809", "B810", "B811", "B812", "B813", "B814", "B815", "B816", "B817", "B818", "B819", "B820", "B821", "B822", "B823", "B824", "B825", "B826", "B827", "B828", "B829", "B830", "B831", "B832", "B833", "B834", "B835", "B836", "B837", "B838", "B839", "B840", "B841", "B842", "B843", "B844", "B845", "B846", "B847", "B848", "B849", "B850", "B851", "B852", "B853", "B854", "B855", "B856", "B857", "B858", "B859", "B860", "B861", "B862", "B863", "B864", "B865", "B866", "B867", "B868", "B869", "B870", "B871", "B872", "B873", "B874", "B875", "B876", "B877", "B878", "B879", "B880", "B881", "B882", "B883", "B884", "B885", "B886", "B887", "B888", "B889", "B890", "B891", "B892", "B893", "B894", "B895", "B896", "B897", "B898", "B899", "B900", "B901", "B902", "B903", "B904", "B905", "B906", "B907", "B908", "B909", "B910", "B911", "B912", "B913", "B914", "B915", "B916", "B917", "B918", "B919", "B920", "B921", "B922", "B923", "B924", "B925", "B926", "B927", "B928", "B929", "B930", "B931", "B932", "B933", "B934", "B935", "B936", "B937", "B938", "B939", "B940", "B941", "B942", "B943", "B944", "B945", "B946", "B947", "B948", "B949", "B950", "B951", "B952", "B953", "B954", "B955", "B956", "B957", "B958", "B959", "B960", "B961", "B962", "B963", "B964", "B965", "B966", "B967", "B968", "B969", "B970", "B971", "B972", "B973", "B974", "B975", "B976", "B977", "B978", "B979", "B980", "B981", "B982", "B983", "B984", "B985", "B986", "B987", "B988", "B989", "B990", "B991", "B992", "B993", "B994", "B995", "B996", "B997", "B998", "B999"]
severity_level = "MEDIUM"
confidence_level = "MEDIUM"
recursive = true

[dependency-groups]
dev = [
    "decouple-types>=1.0.2",
    "django-debug-toolbar>=6.0.0",
    "django-stubs>=5.2.2",
    "line-profiler==5.0.0",
    "pre-commit>=4.2.0",
    "pyright>=1.1.403",
    "ruff>=0.12.5",
    "safety>=3.6.0",
    "snakeviz>=2.2.2",
    "scipy-stubs",
    "celery",
]
all = [
    "django>=5.2.4",
    "line-profiler==5.0.0",
    "mysqlclient>=2.2.7",
    "playwright==1.54.0",
    "psycopg2-binary>=2.9.10",
    "pyright>=1.1.403",
    "python-decouple>=3.8",
    "python-dotenv>=1.1.1",
    "ruff>=0.12.7",
    "decouple-types>=1.0.2",
    "django-debug-toolbar>=6.0.0",
    "django-stubs>=5.2.2",
    "pre-commit>=4.2.0",
    "safety>=3.6.0",
    "snakeviz>=2.2.2",
    "celery",
]
