# Generated by Django 5.2.5 on 2025-08-22 15:20

import apps.common.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VeiculoIpiranga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('status_documentos', models.CharField(blank=True, default='', max_length=255)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CertificadoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('arquivo', models.FileField(storage=apps.common.storage.OriginalFilenameStorage(), upload_to='certificados_veiculos/')),
                ('status', models.CharField(choices=[('pendente', 'Pendente de Envio'), ('enviado', 'Enviado com Sucesso'), ('falha', 'Falha no Envio'), ('falha_max_tentativas', 'Falha: Máximo de Tentativas Atingido'), ('falha_outros_vencidos', 'Falha: Outros Certificados Vencidos')], default='pendente', max_length=30)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='automacao_ipiranga.veiculoipiranga')),
            ],
        ),
    ]
