# Generated by Django 5.2.5 on 2025-08-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacao_ipiranga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadoveiculo',
            name='tentativas_automacao',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='certificadoveiculo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='veiculoipiranga',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
