# Generated by Django 5.2.4 on 2025-08-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacao_ipiranga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculoipiranga',
            name='renavam',
            field=models.CharField(blank=True, default='', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='veiculoipiranga',
            name='status_documentos',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
