# Generated by Django 5.2.5 on 2025-08-11 17:07

import apps.common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacao_ipiranga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadoveiculo',
            name='arquivo',
            field=models.FileField(storage=apps.common.storage.OriginalFilenameStorage(), upload_to='certificados_veiculos/'),
        ),
    ]
