# Generated by Django 5.2.4 on 2025-07-30 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacao_ipiranga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='certificados_veiculos/')),
                ('status', models.CharField(choices=[('pendente', 'Pendente de Envio'), ('enviado', 'Enviado com Sucesso'), ('falha', 'Falha no Envio')], default='pendente', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='automacao_ipiranga.veiculoipiranga')),
            ],
        ),
    ]
