# Generated by Django 5.2.4 on 2025-08-05 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automacao_ipiranga', '0002_alter_veiculoipiranga_renavam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculoipiranga',
            name='renavam',
        ),
    ]
