# Generated by Django 5.2.5 on 2025-08-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacao_ipiranga', '0002_alter_certificadoveiculo_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadoveiculo',
            name='tentativas_automacao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='certificadoveiculo',
            name='tentativas_ocr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='certificadoveiculo',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente de Envio'), ('enviado', 'Enviado com Sucesso'), ('falha', 'Falha no Envio'), ('falha_max_tentativas', 'Falha: Máximo de Tentativas Atingido')], default='pendente', max_length=20),
        ),
    ]
