# Generated by Django 5.2.4 on 2025-07-31 13:35

import apps.common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacao_ipiranga', '0002_certificadoveiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadoveiculo',
            name='arquivo',
            field=models.FileField(storage=apps.common.storage.OriginalFilenameStorage(), upload_to='certificados_veiculos/'),
        ),
    ]
