# Generated by Django 5.2.5 on 2025-08-21 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automacao_ipiranga', '0003_certificadoveiculo_tentativas_automacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificadoveiculo',
            name='tentativas_ocr',
        ),
    ]
