# Generated by Django 5.2.4 on 2025-08-05 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('comando_django', models.CharField(help_text="Nome do comando Django customizado a ser executado (ex: 'automacao_documentos_ipiranga').", max_length=255)),
                ('ativa', models.BooleanField(default=True)),
                ('ultima_execucao', models.DateTimeField(blank=True, null=True)),
                ('proxima_execucao', models.DateTimeField(blank=True, null=True)),
                ('intervalo_execucao_minutos', models.IntegerField(default=60, help_text='Intervalo em minutos entre as execuções.')),
            ],
            options={
                'verbose_name': 'Automação',
                'verbose_name_plural': 'Automações',
            },
        ),
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('url_base', models.URLField(max_length=2000)),
            ],
            options={
                'verbose_name': 'Portal',
                'verbose_name_plural': 'Portais',
            },
        ),
        migrations.CreateModel(
            name='LogExecucaoAutomacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('falha', 'Falha'), ('parcial', 'Sucesso Parcial'), ('alerta', 'Alerta')], max_length=50)),
                ('mensagem', models.TextField(blank=True)),
                ('detalhes_json', models.JSONField(blank=True, help_text='Detalhes adicionais da execução em JSON.', null=True)),
                ('automacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='automacao_documentos.automacao')),
            ],
            options={
                'verbose_name': 'Log de Execução de Automação',
                'verbose_name_plural': 'Logs de Execução de Automações',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('licenca', 'Licença'), ('alvara', 'Alvará'), ('certificado', 'Certificado'), ('outros', 'Outros')], max_length=50)),
                ('numero', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(default='ativo', max_length=50)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='documentos_automatizados/')),
                ('dados_extraidos', models.JSONField(blank=True, help_text='Dados extraídos do documento em formato JSON.', null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='automacao_documentos.portal')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'unique_together': {('portal', 'tipo', 'numero')},
            },
        ),
    ]
