# Generated by Django 5.2.5 on 2025-08-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacao_documentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
