# Generated by Django 5.2.4 on 2025-07-28 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacao_documentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('ultima_execucao', models.DateTimeField(blank=True, null=True)),
                ('proxima_execucao', models.DateTimeField(blank=True, null=True)),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('url_base', models.URLField()),
                ('usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('senha', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogExecucaoAutomacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_execucao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('falha', 'Falha'), ('alerta', 'Alerta')], max_length=20)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('dados_coletados', models.JSONField(blank=True, null=True)),
                ('automacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automacao_documentos.automacao')),
            ],
        ),
        migrations.AddField(
            model_name='automacao',
            name='portal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automacao_documentos.portal'),
        ),
    ]
