# Generated by Django 5.2.4 on 2025-07-30 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automacao_documentos', '0002_automacao_portal_logexecucaoautomacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portal',
            name='senha',
        ),
    ]
