"""Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", cast=Csv())  # type: ignore


# Application definition

INSTALLED_APPS = [
    "debug_toolbar",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
    "apps.dashboard",
    "apps.automacao_ipiranga",
    "apps.automacao_documentos",
    "apps.analise_infracoes",
    "apps.common",
]

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

INTERNAL_IPS = [
    "127.0.0.1",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [  # type: ignore # Added type: ignore
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
    "default": {
        "ENGINE": config("DATABASE_ENGINE", default="django.db.backends.sqlite3"),
        "NAME": config("DATABASE_NAME", default=BASE_DIR / "db.sqlite3"),
    },
    "mysql_source": {
        "ENGINE": config("MYSQL_DB_ENGINE"),
        "NAME": config("MYSQL_DB_NAME"),
        "USER": config("MYSQL_DB_USER"),
        "PASSWORD": config("MYSQL_DB_PASSWORD"),
        "HOST": config("MYSQL_DB_HOST"),
        "PORT": config("MYSQL_DB_PORT", cast=int),
    },
    "postgres_db": {
        "ENGINE": config("POSTGRES_DB_ENGINE"),
        "NAME": config("POSTGRES_DB_NAME"),
        "USER": config("POSTGRES_DB_USER"),
        "PASSWORD": config("POSTGRES_DB_PASSWORD"),
        "HOST": config("POSTGRES_DB_HOST"),
        "PORT": config("POSTGRES_DB_PORT", cast=int),
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Media files (user-uploaded content)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Celery Settings
CELERY_BROKER_URL = config("CELERY_BROKER_URL", default="redis://localhost:6379/0")
CELERY_RESULT_BACKEND = config(
    "CELERY_RESULT_BACKEND", default="redis://localhost:6379/0"
)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "America/Sao_Paulo"

# Celery Settings (Robustness and Production Readiness)
CELERY_TASK_ALWAYS_EAGER = config("CELERY_TASK_ALWAYS_EAGER", default=DEBUG, cast=bool)
CELERY_WORKER_CONCURRENCY = config(
    "CELERY_WORKER_CONCURRENCY", default=4, cast=int
)  # Adjust based on workload
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_STOP = True
CELERY_TASK_TIME_LIMIT = config(
    "CELERY_TASK_TIME_LIMIT", default=300, cast=int
)  # 5 minutes
CELERY_TASK_SOFT_TIME_LIMIT = config(
    "CELERY_TASK_SOFT_TIME_LIMIT", default=240, cast=int
)  # 4 minutes
CELERY_BROKER_TRANSPORT_OPTIONS = {"visibility_timeout": 3600}  # 1 hour for Redis
CELERY_WORKER_MAX_TASKS_PER_CHILD = config(
    "CELERY_WORKER_MAX_TASKS_PER_CHILD", default=100, cast=int
)
CELERY_WORKER_DISABLE_RATE_LIMITS = config(
    "CELERY_WORKER_DISABLE_RATE_LIMITS", default=DEBUG, cast=bool
)

# Automation Settings
IPIRANGA_LOGIN_URL = config(
    "IPIRANGA_LOGIN_URL",
    default="https://sites.redeipiranga.com.br/WAPortranNew/usuario/exibir",
)
IPIRANGA_VENCIDOS_URL = config(
    "IPIRANGA_VENCIDOS_URL",
    default="https://sites.redeipiranga.com.br/WAPortranNew/veiculo/index?situacoesDocumentos=2&status=1,2,3,4,7",
)
IPIRANGA_A_VENCER_URL = config(
    "IPIRANGA_A_VENCER_URL",
    default="https://sites.redeipiranga.com.br/WAPortranNew/veiculo/index?situacoesDocumentos=3&status=1,2,3,4,7",
)
IPIRANGA_DASHBOARD_URL = config(
    "IPIRANGA_DASHBOARD_URL",
    default="https://sites.redeipiranga.com.br/WAPortranNew/dashboard/index",
)

MAX_AUTOMATION_ATTEMPTS = config("MAX_AUTOMATION_ATTEMPTS", default=3, cast=int)


# MySQL Infractions Table
MYSQL_INFRACOES_TABLE = config("MYSQL_INFRACOES_TABLE", default="tbl_infracoes_exemplo")

POSTGRES_DB_ALIAS = config("POSTGRES_DB_ALIAS", default="postgres_db")

# Logging configuration
LOG_ROOT = BASE_DIR / "logs"
LOG_ROOT.mkdir(parents=True, exist_ok=True)  # Ensure the logs directory exists

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {asctime} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_ROOT / "orchestra.log",
            "maxBytes": 1024 * 1024 * 5,  # 5 MB
            "backupCount": 5,
            "formatter": "verbose",
        },
        "automation_file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_ROOT / "automation.log",
            "maxBytes": 1024 * 1024 * 10,  # 10 MB
            "backupCount": 10,
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "apps": {  # Logger para todos os apps customizados
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "apps.automacao_ipiranga": {  # Logger específico para a automação
            "handlers": ["console", "automation_file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "apps.dashboard": {  # Logger específico para o dashboard
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "celery": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "celery.task": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": "DEBUG",
    },
}
