# Generated by Django 5.2.4 on 2025-08-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa_veiculo', models.CharField(help_text='Placa do veículo que cometeu a infração.', max_length=10)),
                ('data_hora', models.DateTimeField(help_text='Data e hora em que a infração ocorreu.')),
                ('local', models.CharField(help_text='Local da infração.', max_length=255)),
                ('tipo_infracao', models.CharField(help_text='Descrição do tipo de infração.', max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor da multa.', max_digits=10)),
                ('pontos_carteira', models.IntegerField(help_text='Número de pontos atribuídos à carteira.')),
                ('status', models.CharField(default='nova', help_text='Status da infração (ex: nova, em análise, paga).', max_length=50)),
                ('dados_origem', models.JSONField(help_text='Dados brutos originais do banco de dados de origem.')),
            ],
            options={
                'verbose_name': 'Infração',
                'verbose_name_plural': 'Infrações',
                'ordering': ['-data_hora'],
            },
        ),
    ]
